apiVersion: security.antrea.tanzu.vmware.com/v1alpha1
kind: ClusterNetworkPolicy
metadata:
  name: acnp-with-cp
spec:
  priority: 8
  tier: securityops
  appliedTo:
    - group: "cluster-group-01"
  ingress:
    - action: Allow
      from:
        - group: "cluster-group-03"
      ports:
        - protocol: TCP
          port: 8080
          endPort: 9000
        - protocol: TCP
          port: 6379
      name: AllowedCG
      enableLogging: false
  egress:
    - action: Drop
      to:
        - group: "ip-block-cluster-group"
      ports:
        - protocol: TCP
          port: 5978
      name: DropToThirdParty
      enableLogging: true